Active=Active
Automation=Automation
Cancelled=Cancelled
Closed=Closed
Completed=Completed
Development=Development
Future=Future
In\ Progress=In Progress
Manpower\ Supply=Manpower Supply
On\ Hold=On Hold
Others=Others
Past=Past
Program\ Management=Program Management
Ready\ To\ Start=Ready To Start
SOW\ Type=SOW Type
Testing=Testing